### ISSUE TITLE
good stuff

### ISSUE THREAD

**Issue by evanpurkhiser** [radian-software/venmo-auto-transfer#2]
Just wanted to share my experience! I've written something similar: https://github.com/evanpurkhiser/venmo-auto-cashout

I have been running this [as a systemd.timer](https://github.com/evanpurkhiser/ansible-personal/blob/main/roles/machines/server/files/systemd/venmo-auto-cashout.timer) **every minute** for almost the last year and Venmo still has not noticed.

I specifically want it to run very often since I really like my venmo transactions to reflect exactly as line items in my bank account, so I can correctly split the transactions they are offsetting.

Thought it might be useful to share!

**Comment by raxod502** [comment]
Awesome project! I added a "See also" section to mention it: https://github.com/radian-software/venmo-auto-transfer/commit/f78f6cc7385dfc06b4ff2ee3907079934d5a25fb
