### ISSUE TITLE
Additional authentication is required

### ISSUE THREAD

**Issue by Seltonu** [radian-software/venmo-auto-transfer#7]
Hello! I've installed poetry and attempted to run the auto transfer, but I get the following output error

```
 ./venmo_auto_transfer.bash 
venmo_auto_transfer: attempting to login to Venmo as [USER] with password and bank account number
venmo_auto_transfer: {"issue":"Additional authentication is required","code":81109,"title":"Error","secret":"[SECRET]"}
venmo_auto_transfer: got unexpected status code 400 on /login POST
```

If I try with option -v I get an OAuth2 error

```
./venmo_auto_transfer.bash -v
venmo_auto_transfer: attempting to login to Venmo as [USER] with password and bank account number
venmo_auto_transfer: {"issue":"OAuth2 Exception: Unauthorized action..","code":240,"title":"Error"}
venmo_auto_transfer: got unexpected status code 400 on /login POST
```

Any ideas what might be going wrong here?

**Comment by raxod502** [comment]
Venmo has decided to block your account. They did that to me too, as well as to [thousands of other users](https://old.reddit.com/r/venmo/comments/16bzr4e/oauth2_exception_unauthorized_action/). So far, Venmo has refused to elaborate on the reason they have decided to lock users out of their funds, and customer support agents refuse to provide any assistance.

**Comment by Seltonu** [comment]
@raxod502 oddly enough without changing anything at all on my end, the problem seems to have fixed itself as of today and I was able to transfer my balance with the script. Hopefully this means Venmo is aware/fixing the problem for others as well?

Though notably, I didn't have any issues with signing in on mobile app or browser like some of the commenters did

In any case, closing this issue because it sounds like the issue is with venmo exclusively and not this tool. Thank you!

**Comment by raxod502** [comment]
I've been in communication with Venmo about this issue for some time. So far, 55 emails have been exchanged with several dozen support agents over 8 weeks (plus numerous hours of phone calls), and the case is still ongoing. At this point, I feel quite confident that Venmo as a company has no interest in providing any assistance or resolution to their users. Sounds like you may have gotten lucky though and the automated systems decided to unflag your account. That happened to me from time to time as well.
